version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: nest123
      POSTGRES_DB: nestDB
    networks:
      - nestApi
networks:
  nestApi: